name: runner-cloudflared-tunnel
on:
  workflow_dispatch:
  push:
    paths:
      - "bin/**"
      - "src/**"
      - "README.md"
      - "package.json"
      - ".github/workflows/run-runner-cloudflared-tunnel.yml"
permissions:
  id-token: write # Required for OIDC
  contents: write # Thêm dòng này để có quyền push

jobs:
  runner-cloudflared-tunnel:
    runs-on: ubuntu-latest
    timeout-minutes: 3 # Set the maximum runtime for this job to 20 minutes
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true # CHỈ CẦN CÁI NÀY để giữ token cho push
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - name: npm-install
        run: |
          npm i
          npm i -g @tltdh61/dotenvrtdb
          npm i -g @hugginroonin/runner-add-ssh
          npm i -g @ongtrieuhau861457/runner-tailscale-sync
          npm i -g @ongtrieuhau861457/runner-keep-alive
      - name: runner-cloudflared-tunnel
        env:
          DOTENVRTDB_URL_RUNNER: ${{ secrets.DOTENVRTDB_URL_RUNNER }}
        run: |
          dotenvrtdb --eUrl "$DOTENVRTDB_URL_RUNNER" -- runner-add-ssh --verbose
          dotenvrtdb --eUrl "$DOTENVRTDB_URL_RUNNER" -- runner-tailscale-sync --verbose
          dotenvrtdb --eUrl "$DOTENVRTDB_URL_RUNNER" -- node ./bin/cloudflared-tunnel-start.js --verbose
      - name: ⏳ Keep Alive
        run: |
          runner-keep-alive --interval 60 --services All
